version: '3.7'

services:

  shopping_car:
    container_name: ShoppingCar
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - 4000:4000